[package]
name = "fit-tech-backend"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4"
dotenvy="0.15"
env_logger = "0.11"
log = "0.4"

sea-orm = { version = "1.1.16", features = ["sqlx-postgres", "runtime-tokio-rustls", "macros"]}
serde = "1.0.227"

